### STA 208 HW0
### Runtian Zhu 919013175
### 3/30/2022

In [412]:
import os
import numpy as np
import pandas as pd

## Question 1

### 1.a

In [367]:
u = np.array([1,2,3,3,2,1])# create a vector

In [368]:
u = u.reshape((-1,1))# turn into col-vector

In [369]:
print(u)

[[1]
 [2]
 [3]
 [3]
 [2]
 [1]]


In [370]:
id_mat = np.identity(len(u))# create an identity matrix

In [371]:
U = id_mat - (2/(u.transpose()@u))*(u@u.transpose()) # use @ for matrix multiplication

$\mathbf{U}$ is

In [372]:
print(U)

[[ 0.92857143 -0.14285714 -0.21428571 -0.21428571 -0.14285714 -0.07142857]
 [-0.14285714  0.71428571 -0.42857143 -0.42857143 -0.28571429 -0.14285714]
 [-0.21428571 -0.42857143  0.35714286 -0.64285714 -0.42857143 -0.21428571]
 [-0.21428571 -0.42857143 -0.64285714  0.35714286 -0.42857143 -0.21428571]
 [-0.14285714 -0.28571429 -0.42857143 -0.42857143  0.71428571 -0.14285714]
 [-0.07142857 -0.14285714 -0.21428571 -0.21428571 -0.14285714  0.92857143]]


### 1.b

In [373]:
C = U@U # matrix multiplication

$\mathbf{C}$ is

In [374]:
print(C)

[[ 1.00000000e+00 -2.46401539e-17 -5.55111512e-17 -4.38991247e-17
  -2.77555756e-17 -1.92589708e-17]
 [-2.46401539e-17  1.00000000e+00 -7.59030027e-17 -1.11022302e-16
  -4.48195902e-17 -2.77555756e-17]
 [-5.55111512e-17 -7.59030027e-17  1.00000000e+00 -7.22211406e-17
  -1.11022302e-16 -4.48903953e-17]
 [-4.38991247e-17 -1.11022302e-16 -7.22211406e-17  1.00000000e+00
  -8.97807905e-17 -8.32667268e-17]
 [-2.08166817e-17 -5.55111512e-17 -9.71445147e-17 -5.55111512e-17
   1.00000000e+00 -4.16333634e-17]
 [-1.38777878e-17 -2.77555756e-17 -5.55111512e-17 -8.32667268e-17
  -4.16333634e-17  1.00000000e+00]]


In [375]:
def max_min_off_diagonal(mat):# define a function to get max and min entries that are not on main or secondary diagonal
    max_off_diagonal = mat[0][0]# assign initial values
    min_off_diagonal = mat[0][0]
    for i in range(1,len(mat)):# i starts from 1 as we specify initial value from index 0
        for j in range(1,len(mat[0])):
            if((i != j) and (i+j != len(mat)-1)):#not in main diagonal or in secondary diagonal
                if(mat[i][j] < min_off_diagonal):
                    min_off_diagonal = mat[i][j]
                if(mat[i][j] > max_off_diagonal):
                    max_off_diagonal = mat[i][j]
    print('The max entry in off-diagonal is', max_off_diag,\
                  'The min entry in off-diagonal is.', format(min_off_diag,'.5E'))

In [376]:
max_min_off_diagonal(C)

The max entry in off-diagonal is 1.0 The min entry in off-diagonal is. -1.11022E-16


### 1.c

In [377]:
def max_min_diagonal(mat):
    max_diagonal = mat[0][0]
    min_diagonal = mat[0][0]
    for i in range(1,len(mat)):
        for j in range(1,len(mat[0])):
            if((i == j) or (i+j == len(mat)-1)):#either in primary diagonal or in secondary diagonal
                if(mat[i][j] < min_diagonal):
                    min_diagonal = mat[i][j]
                if(mat[i][j] > max_diagonal):
                    max_diagonal = mat[i][j]
    print('The max entry in diagonal is', max_diagonal,\
                  'The min entry in diagonal is.', format(min_diagonal,'.5E'))

In [378]:
max_min_diagonal(C)

The max entry in diagonal is 1.0 The min entry in diagonal is. -7.22211E-17


### 1.d

Use 3 methods to get the $\mathbf{Uu}$.

In [379]:
U.dot(u)

array([[-1.],
       [-2.],
       [-3.],
       [-3.],
       [-2.],
       [-1.]])

In [380]:
np.dot(U,u)

array([[-1.],
       [-2.],
       [-3.],
       [-3.],
       [-2.],
       [-1.]])

In [381]:
U@u

array([[-1.],
       [-2.],
       [-3.],
       [-3.],
       [-2.],
       [-1.]])

### 1.e

In [382]:
sum(abs(U[1,:]))

2.142857142857143

In [386]:
def max_row_abs_sum(mat):
    abs_sum_row_max = sum(abs(mat[0,:])) # initial condition, the sum of 1st row
    coord = 0 # by default, 1st row has largest sum
    same_value = [] # an empty list in case there are rows have same sum of absolute
    for i in range(1,len(mat)):
        abs_sum_row_i = sum(abs(mat[i,:]))
        if(abs_sum_row_max == abs_sum_row_i):
            same_value.append(i)
        if(abs_sum_row_max < abs_sum_row_i):
            abs_sum_row_max = abs_sum_row_i
            coord = i # python starts indexing from 0
    x = np.array(same_value) # turn the list to an array
    x += 1 # get the row number
    print('Row',coord+1,'has largest sum of absolute value of entries.',\
          'Row',x,'has the same value.')

In [387]:
max_row_abs_sum(U)

Row 3 has largest sum of absolute value of entries. Row [4] has the same value.


Manually check the result.

In [388]:
for i in range(0,6):
    print(sum(abs(U[i,:])))

1.714285714285714
2.142857142857143
2.2857142857142856
2.2857142857142856
2.142857142857143
1.7142857142857142


### 1.f 

In [389]:
print('The thrid row of U is', U[3,:].tolist())

The thrid row of U is [-0.21428571428571427, -0.42857142857142855, -0.6428571428571428, 0.3571428571428572, -0.42857142857142855, -0.21428571428571427]


### 1.g

Elements below the diagonal of 2nd column in $\mathbf{C}$ 

In [390]:
for i in range(2,len(C)):
    print(C[i][1])

-7.590300270396478e-17
-1.1102230246251565e-16
-5.551115123125783e-17
-2.7755575615628914e-17


For reference, $\mathbf{C}$ is

In [391]:
print(C)

[[ 1.00000000e+00 -2.46401539e-17 -5.55111512e-17 -4.38991247e-17
  -2.77555756e-17 -1.92589708e-17]
 [-2.46401539e-17  1.00000000e+00 -7.59030027e-17 -1.11022302e-16
  -4.48195902e-17 -2.77555756e-17]
 [-5.55111512e-17 -7.59030027e-17  1.00000000e+00 -7.22211406e-17
  -1.11022302e-16 -4.48903953e-17]
 [-4.38991247e-17 -1.11022302e-16 -7.22211406e-17  1.00000000e+00
  -8.97807905e-17 -8.32667268e-17]
 [-2.08166817e-17 -5.55111512e-17 -9.71445147e-17 -5.55111512e-17
   1.00000000e+00 -4.16333634e-17]
 [-1.38777878e-17 -2.77555756e-17 -5.55111512e-17 -8.32667268e-17
  -4.16333634e-17  1.00000000e+00]]


### 1.h

$\mathbf{A}$ is

In [393]:
A = U[:,0:3]
print(A)

[[ 0.92857143 -0.14285714 -0.21428571]
 [-0.14285714  0.71428571 -0.42857143]
 [-0.21428571 -0.42857143  0.35714286]
 [-0.21428571 -0.42857143 -0.64285714]
 [-0.14285714 -0.28571429 -0.42857143]
 [-0.07142857 -0.14285714 -0.21428571]]


$\mathbf{P}$ is

In [395]:
P = np.dot(A,A.T)
print(P)

[[ 9.28571429e-01 -1.42857143e-01 -2.14285714e-01 -3.54025199e-17
  -2.88884563e-17 -1.44442281e-17]
 [-1.42857143e-01  7.14285714e-01 -4.28571429e-01 -1.52938886e-17
  -2.26576127e-18 -1.13288064e-18]
 [-2.14285714e-01 -4.28571429e-01  3.57142857e-01 -4.07837029e-17
  -4.30494642e-17 -2.15247321e-17]
 [-3.54025199e-17 -1.52938886e-17 -4.07837029e-17  6.42857143e-01
   4.28571429e-01  2.14285714e-01]
 [-2.88884563e-17 -2.26576127e-18 -4.30494642e-17  4.28571429e-01
   2.85714286e-01  1.42857143e-01]
 [-1.44442281e-17 -1.13288064e-18 -2.15247321e-17  2.14285714e-01
   1.42857143e-01  7.14285714e-02]]


### 1.i

The result is virtually 0 with rounded down to 4 decimal places.

In [403]:
print(np.round(np.dot(P,P)-P,4))

[[ 0. -0.  0. -0. -0. -0.]
 [-0.  0. -0.  0.  0.  0.]
 [ 0. -0. -0. -0.  0.  0.]
 [-0.  0. -0. -0. -0. -0.]
 [-0.  0.  0. -0. -0. -0.]
 [-0.  0.  0. -0. -0. -0.]]


### 1.j

For reference, $\mathbf{U}$ is

In [405]:
print(U)

[[ 0.92857143 -0.14285714 -0.21428571 -0.21428571 -0.14285714 -0.07142857]
 [-0.14285714  0.71428571 -0.42857143 -0.42857143 -0.28571429 -0.14285714]
 [-0.21428571 -0.42857143  0.35714286 -0.64285714 -0.42857143 -0.21428571]
 [-0.21428571 -0.42857143 -0.64285714  0.35714286 -0.42857143 -0.21428571]
 [-0.14285714 -0.28571429 -0.42857143 -0.42857143  0.71428571 -0.14285714]
 [-0.07142857 -0.14285714 -0.21428571 -0.21428571 -0.14285714  0.92857143]]


In [404]:
B = U[:,-4:-1]
print(B)

[[-0.21428571 -0.21428571 -0.14285714]
 [-0.42857143 -0.42857143 -0.28571429]
 [ 0.35714286 -0.64285714 -0.42857143]
 [-0.64285714  0.35714286 -0.42857143]
 [-0.42857143 -0.42857143  0.71428571]
 [-0.21428571 -0.21428571 -0.14285714]]


$\mathbf{Q}$ is

In [410]:
B.dot(B.T)

array([[ 0.1122449 ,  0.2244898 ,  0.12244898,  0.12244898,  0.08163265,
         0.1122449 ],
       [ 0.2244898 ,  0.44897959,  0.24489796,  0.24489796,  0.16326531,
         0.2244898 ],
       [ 0.12244898,  0.24489796,  0.7244898 , -0.2755102 , -0.18367347,
         0.12244898],
       [ 0.12244898,  0.24489796, -0.2755102 ,  0.7244898 , -0.18367347,
         0.12244898],
       [ 0.08163265,  0.16326531, -0.18367347, -0.18367347,  0.87755102,
         0.08163265],
       [ 0.1122449 ,  0.2244898 ,  0.12244898,  0.12244898,  0.08163265,
         0.1122449 ]])

### 1.k

In [ ]:
The result is virtually 0 with rounded down to 4 decimal places.

In [409]:
print(np.round(np.dot(Q,Q)-Q,4))

[[-0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0.]
 [-0. -0. -0.  0. -0. -0.]
 [-0. -0.  0. -0.  0. -0.]
 [-0. -0. -0. -0.  0. -0.]
 [-0. -0. -0. -0. -0. -0.]]


### 1.l

$\mathbf{P}+\mathbf{Q}$ is

In [411]:
print(P+Q)

[[ 1.04081633  0.08163265 -0.09183673  0.12244898  0.08163265  0.1122449 ]
 [ 0.08163265  1.16326531 -0.18367347  0.24489796  0.16326531  0.2244898 ]
 [-0.09183673 -0.18367347  1.08163265 -0.2755102  -0.18367347  0.12244898]
 [ 0.12244898  0.24489796 -0.2755102   1.36734694  0.24489796  0.33673469]
 [ 0.08163265  0.16326531 -0.18367347  0.24489796  1.16326531  0.2244898 ]
 [ 0.1122449   0.2244898   0.12244898  0.33673469  0.2244898   0.18367347]]


## Question 2

data = np.genfromtxt('D:\\UCD\\2022S\\208\\hw0\\hw0\\oringp.dat')

In [427]:
print(data[:,:],\
     type(data),\
     np.shape(data),sep='\n')

[[ 1. nan  6.  0. 66.]
 [ 2. nan  6.  1. 70.]
 [ 3. nan  6.  0. 69.]
 [ 5. nan  6.  0. 68.]
 [ 6. nan  6.  0. 67.]
 [ 7. nan  6.  0. 72.]
 [ 8. nan  6.  0. 73.]
 [ 9. nan  6.  0. 70.]
 [nan nan  6.  1. 57.]
 [nan nan  6.  1. 63.]
 [nan nan  6.  1. 70.]
 [nan nan  6.  0. 78.]
 [nan nan  6.  0. 67.]
 [nan nan  6.  3. 53.]
 [nan nan  6.  0. 67.]
 [nan nan  6.  0. 75.]
 [nan nan  6.  0. 70.]
 [nan nan  6.  0. 81.]
 [nan nan  6.  0. 76.]
 [nan nan  6.  0. 79.]
 [nan nan  6.  2. 75.]
 [nan nan  6.  0. 76.]
 [nan nan  6.  1. 58.]
 [nan nan  6. nan 31.]]
<class 'numpy.ndarray'>
(24, 5)


Remove the last observation.

In [428]:
data = data[:-1,:]
print(data)

[[ 1. nan  6.  0. 66.]
 [ 2. nan  6.  1. 70.]
 [ 3. nan  6.  0. 69.]
 [ 5. nan  6.  0. 68.]
 [ 6. nan  6.  0. 67.]
 [ 7. nan  6.  0. 72.]
 [ 8. nan  6.  0. 73.]
 [ 9. nan  6.  0. 70.]
 [nan nan  6.  1. 57.]
 [nan nan  6.  1. 63.]
 [nan nan  6.  1. 70.]
 [nan nan  6.  0. 78.]
 [nan nan  6.  0. 67.]
 [nan nan  6.  3. 53.]
 [nan nan  6.  0. 67.]
 [nan nan  6.  0. 75.]
 [nan nan  6.  0. 70.]
 [nan nan  6.  0. 81.]
 [nan nan  6.  0. 76.]
 [nan nan  6.  0. 79.]
 [nan nan  6.  2. 75.]
 [nan nan  6.  0. 76.]
 [nan nan  6.  1. 58.]]


In [433]:
data[:,3]

array([0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 3., 0., 0., 0.,
       0., 0., 0., 2., 0., 1.])

In [438]:
from scipy.stats import pearsonr
corr = pearsonr(data[:,3],data[:,4])
print('The correlation coefficient is %.4f.'%corr[0])

The correlation coefficient is -0.5613.


## Question 3

In [445]:
import math as m
np.random.seed(0)

In [444]:
def dmvnorm_lowrank(y,mu,Z,sigma0,sigma1,log= 'FALSE'):# default value for log is FALSE
    n = len(mu)
    id_mat = np.identity(n)
    det = np.linalg.det(sigma1**2*Z@Z.T+pow(sigma0,2)*id_mat)
    kernel = sigma1**2*Z@Z.T+sigma0**2*id_mat
    if(log == 'TRUE'):
        density = (2*m.pi)**(-n/2)*(det)**(-1/2)*m.exp((-1/2)*(y-mu).T@np.linalg.inv(kernel)@(y-mu))
    if(log == 'FALSE'):
        density = (-n/2)*m.log(2*m.pi)-(1/2)*m.log(det)-1/2*(y-mu).T@np.linalg.inv(kernel)@(y-mu)
    print('The density of given input is',density)

In [ ]:
# input simulation
n = # number of obs
p = # number of fixed effects
q = # number of random effects
epsilon = 